### ISSUE TITLE
Rename to js-function-context-this-diagnostic?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-function-context-this-diagnostic#102]
Parallel name of talk?

@ga-wdi-boston/core

**Comment by RealWeeks** [comment]
@gaand has to be changed. The current naming doesn't make any sense

**Comment by RealWeeks** [comment]
@ga-wdi-boston/core This change has been made to reflect naming of the talk.  Only logic thing to do.  Please comment of revert if you disagree.
