### ISSUE TITLE
Add jasmine back to package.json or switch tests over to mocha

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-function-context-this-diagnostic#120]
@ga-wdi-boston/core

**Comment by tuckyeah** [comment]
Based on [some googling](http://floatleft.com/notebook/testing-your-javascript-with-jasmine-and-grunt/), I updated my Gruntfile.js to look like:

```
module.exports = function(grunt) {

  grunt.initConfig({
    jasmine: {
      src: './lib/diagnostic.js',
      specs: './specs/diagnostic.spec.js'
    }
  });

  // Register tasks.
grunt.loadNpmTasks('grunt-jasmine-runner');

// Default task.
grunt.registerTask('default', 'jasmine');

  require('time-grunt')(grunt);
  require('load-grunt-config')(grunt);

};
```

and did `npm install grunt-jasmine-runner` but still no dice :(

In the console it says:

```
Loading "jasmine.js" tasks...ERROR
>> TypeError: Cannot read property '_' of undefined
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property '_' of undefined
```

I'm sure I'm missing a step or several, just wanted to point out the steps I did take in case it was helpful!

**Comment by jrhorn424** [comment]
We don't use the Gruntfile like that in our program. You can dig in the history of `browser-template` if you'd like to play around. I think you just need to add the `jasmine*` dependencies back to `package.json` and then try `npm install` again.

**Comment by gaand** [comment]
Test should be updated to `mocha`.
