### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/js-function-context-this-diagnostic#54]
> Insert a line between 7 and 8 that invokes `fire`. 

Is this asking students to create a property on `deathStar` to hold the result of `deathStar.fire`?
i.e.

``` javascript
/*1*/ var alderaan = { name: 'Alderaan' };
/*2*/ var deathStar = {
/*3*/   laserQuantity: 1,
/*4*/   laserSize: "huge",
/*5*/   fire: function fire(){
/*6*/     conosole.log(this);
/*7*/   },
          iife: (this.fire)()
/*8*/ };
```

**Comment by jrhorn424** [comment]
Can I get a line reference to the assessment file, like this? https://github.com/ga-wdi-boston/js-scope-context-assessment/blob/master/src/assessment.js#L51

I don't see what you're talking about.

**Comment by jrhorn424** [comment]
If you're referring to q5 (should be q3, actually), the solution is not to edit the code.

It's to use `deathstar.fire.call(alderaan)`.

**Comment by jrhorn424** [comment]
Added tests. Can this be closed @MattB-GA-Boston? I still don't understand the confusion. There are two different code snippets, and the one you pasted was for the third question, but the question that asks to imagine a new function is the first question, with a different piece of code.

**Comment by RealWeeks** [comment]
@MattB-GA-Boston @jrhorn424 Following up on this being closed
